# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
resources:
  - name: Tailspin Key
    type: Microsoft.Windows/Registry
    properties:
      keyPath:   HKCU\tailspin
  - name: Tailspin - Update automatically
    type: Microsoft.Windows/Registry
    properties:
      keyPath:   HKCU\tailspin\updates
      valueName: automatic
      valueData:
        String: enable

  # Commented out due to a bug in the resource
  # - name: Tailspin - Update every 30 days
  #   type: Microsoft.Windows/Registry
  #   properties:
  #     keyPath:   HKCU\tailspin\updates
  #     valueName: frequency
  #     valueData:
  #       DWord: 30
