blank_issues_enabled: false
contact_links:
  - name: Quality Contributions
    url: https://learn.microsoft.com/powershell/scripting/community/contributing/quality-improvements
    about: >-
      If you'd like to commit to improving quality for the documentation, before filing an issue,
      check the info and instructions.
  - name: PowerShell Product Feedback
    url: https://github.com/PowerShell/PowerShell/issues/new/choose
    about: Please open feature requests for current PowerShell here.
  - name: DSC Product Feedback
    url: https://github.com/PowerShell/PSDesiredStateConfiguration/issues/new/choose
    about: Please open feature requests for DSC here.
  - name: Where to find help for DSC
    url: https://dsccommunity.org/help/
    about: DSC support resources
