# yaml-language-server: $schema=https://aka.ms/dsc/schemas/v3/bundled/config/document.vscode.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
  - name: Managed key
    type: Microsoft.Windows/Registry
    properties:
      _exist: true
      keyPath: HKCU\DscExamples\ManagedKey
  - name: Managed value
    type: Microsoft.Windows/Registry
    properties:
      _exist:  true
      keyPath: HKCU\DscExamples
      valueName: ManagedValue
      valueData:
        String: Default
