# This workflow verifies that an author submitting a pull request to the main
# branch to modify repository files is authorized to do so; only users with
# maintainer or admin rights may modify the actions or the workflow definitions.
name: Authorization
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "*.yml"
      - .github/**
      - .openpublishing*
      - LICENSE*
      - dsc/docfx.json
      - dsc/mapping/**
      - ThirdPartyNotices
permissions:
  contents: read
jobs:
  Test:
    name: Check Repo File Permissions
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Authorized to Modify Repo Files?
        uses: MicrosoftDocs/PowerShell-Docs/.github/actions/verification/authorization/v1@main
        with:
          token: ${{ github.token }}
          target: |
            path:
              *.yml
              .github/**
              .openpublishing*
              LICENSE*
              dsc/docfx.json
              dsc/mapping/**
              ThirdPartyNotices
